name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: awraris
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
